# Generated by Django 3.0.7 on 2021-01-06 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, verbose_name='number')),
                ('code', models.CharField(max_length=256, verbose_name='code')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('approved_date', models.DateTimeField()),
                ('currency_id', models.IntegerField()),
                ('partner_id', models.IntegerField()),
                ('partner_address_id', models.IntegerField()),
                ('notes', models.TextField()),
                ('dimm_1', models.IntegerField()),
                ('dimm_2', models.IntegerField()),
                ('dimm_3', models.IntegerField()),
                ('dimm_4', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('self_partner_id', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('responsible_id', models.IntegerField()),
                ('repartization_key', models.TextField()),
                ('renewel_type_id', models.IntegerField()),
                ('renewel_end_date', models.DateTimeField()),
                ('penalty_percent_day', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
