# Generated by Django 3.0.7 on 2021-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20210106_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
